---
title: "RMarkDown_Eksamen"
author: "Gruppe24"
date: "2024-05-23"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

dir.create("data")
install.packages("tidyverse")
install.packages("here")
install.packages("dplyr")
install.packages("tidyr")
install.packages("ggplot2")
install.packages("reader")
library(tidyverse)
library(here)
library("dplyr")
library(tidyr)
library("ggplot2")
library("reader")

aarhus_census <- read.csv(here("data_fælles","dataset_clean.csv"))
```


```{r}
aarhus_data <- aarhus_census %>%
mutate(Erhvervskategori = case_when(
erhverv %in% c("Geheime Raadjnde af Woyda", "Arbeyder i litteratur", "provst", "geheimeråd og stiftamtmand", "Baron, kammerherre og amtmand", "Præste enke", "Baronesse", "Bestyrer", "Grevinde og har 400 Rdr i Enke Pension", "Biskop", "Rådmand", "Betjent", "Billeteur", "Branddirektør", "Hendes Mand har fast Tjeneste", "Skolelærer", "Hospitalsforstander", "Cancellirådinde, - lever af det, hun har", "Candedatus Theologies", "Cappelan", "Consumptionsbetjent", "Contoirbetjent", "Degn", "Dommer", "Informator", "Inspecteur", "Enke Degn", "Enke Provstinde", "Etatsraadinde", "Jurist", "Sognepræst", "Kammerherre", "Kammerråd", "Foged", "Kornmåler", "Formuende", "Forpagter", "Landmaaler", "Lever af Formue", "Lever af sin Formue", "Forvalter", "Fuldmægtig", "stiftsphysicus", "stiftsrevisor", "Student", "Lægdsmand", "Læge", "Ved Landvæsenet", "Marqueur", "Told", "toldkasserer", "Organist") ~ "Embedsmænd, funktionære og liberale erhverv",
erhverv%in% c("Apoteker", "Postmester, Kiøb- og Værtshusmusmand, Gæstgiver og prokurator", "Handler", "Brændevinsmand", "Købmand", "Værtshusmand") ~ "Købmænd",
erhverv %in% c("Gartner", "Baber", "Bager", "Bagerenke", "Glarmester", "Rebslager", "Skoflikker", "Skomager", "Skrædder", "Håndværksmager", "Slagter", "Smed", "Snedker", "Kok", "Mester", "Teglbrænder") ~ "Håndværksmestre",
erhverv %in% c("Apotekerdreng", "Assistent", "Garver", "Skoleelev", "Giør Stoele", "Gjørtler", "Blegmand", "Blikkenslager", "Bogbinder", "Byens tambour", "Bødker", "Hugger", "I Lære", "Drejer", "Farver", "Favn Brænde Kiøer", "Mahler og Gartner", "Tømrer", "Svend") ~ "Svend eller i Lære",
erhverv %in% c( "Gadekører", "Hjulmand", "klubvært", "Kromand", "Kudsk", "Forridder", "Vognmand", "Opvarterske for de syge") ~ "Avlsmænd, vognmænd og værtsholdere",
erhverv %in% c("Skipper", "Fiskemester ved grevskabet Frijsenborg", "Fisker", "Lods", "Matros") ~ "Skippere, jægere, fiskere",
erhverv %in% c("Graver", "Arbejder ved Canalen", "Går med bagerkurven", "Spinder", "Rådstuebud", "Baademand", "Skovridder", "Hyrde", "Høker", "Skærsliber", "Jordemoder", "Examineret Foster Moder", "Kalkslager", "Klokker", "Stadsmusikant", "Krambodsdreng", "Stenkløver og -hugger, beboer et Markhuus, er Landeværnsmand", "Lever af at stampe Vadmel", "Fostermoder", "Stenpikker", "Lever af sit Arbejde", "Faar Løn", "strømpevæver", "Væver", "Vægter", "Volunteur", "Læser for Børn i Byen", "strøekone ved Domkirken", "Vaskekone", "Substitut", "Syerske", "Mejerske", "Tærsker", "Træskomand", "Natmand", "Trykker", "Tobaksspinder", "Nærer sig ved Haandarbejde") ~ "Ufaglært arbejder",
erhverv %in% c("General Krigs Commisair, Rigs-Greve", "Skytte", "Rytter", "Soldat", "fhv. militærmand med årlig pension", "Overordnet Soldat") ~ "Militært personel",
erhverv %in% c("Afskediget", "Antagen til opdragelse", "Besvangret", "Enke", "Fattig", "formedels sin solgte gaard", "Ledig", "Lever af sine midler", "Opdrages i huset") ~ "Uden erhverv",
erhverv %in% c("Rygter paa Gersdorrslund", "Huusholderske", "Stuekone", "Tyende", "Tjener Familie") ~ "Tyende",
erhverv %in% c("Aftægtsfolk", "Pension", "Frit underholdt", "Logerende", "Understøtter Familiemedlem", "Understøttelse af Private", "Understøttelse af Familie", "nyder Ophold", "nyder Ophold af gaarden") ~ "Aftægtsfolk/pensionerede",
erhverv %in% c("Proprietair", "Har en Mølle i Fæste", "Boelsmand", "Bonde og Gaardbeboer", "Huusmand", "Huusmand med Jord", "Huusmand og andet Erhverv", "Enke med Jord", "Stamherre", "Møller") ~ "Bonde med jord",
erhverv %in% c("Daglejer", "Inderste", "Jordløs Huusmand") ~ "Bonde uden jord",
erhverv %in% c("Hospitalslem", "Vanvittig") ~ "Syge og vanføre",
erhverv %in% c("Tigger") ~ "Tiggere",
erhverv %in% c("Nyder Almisse") ~ "Almissemodtager",

famstand%in% c("Tyende") ~ "Tyende",
grepl("opholds", famstand) ~ "Aftægtsfolk/pensionerede",
grepl("Opholds", famstand) ~ "Aftægtsfolk/pensionerede",


TRUE ~ "Ukendt"

))
```




```{r}
Koordinator <- readxl::read_excel (here("data_fælles","Sogn_Koordinator.xlsx"))
Aarhus_data_K <- aarhus_data
Aarhus_data_K <-  left_join(aarhus_data, Koordinator, by = "sogn")
```




```{r}
procent_køn_erhverv <- aarhus_data %>%
  filter(koen != "") %>% 
  count(koen, Erhvervskategori) %>% 
  group_by(Erhvervskategori) %>% 
  mutate(koen_procent = (n/sum(n))*100)
   
procent_køn_erhverv %>% 
  ggplot(aes(x = Erhvervskategori, y = koen_procent, fill = koen)) +
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = -45, hjust = 0)) +
  scale_fill_manual(values = c("dodgerblue", "orange")) + 
  labs(title = "Procentfordeling af køn i erhvervskategorier",
       fill = "Køn",
       x = "Erhvervskategori",
       y = "Procent")
```



```{r}
procent_civilstand_erhverv <- aarhus_data %>% 
  filter(civilstand != "") %>% 
  count(civilstand, Erhvervskategori) %>% 
  group_by(Erhvervskategori) %>% 
  mutate(civilstand_procent = (n/sum(n))*100)

procent_civilstand_erhverv %>% 
  ggplot(aes(x = Erhvervskategori, y = civilstand_procent, fill = civilstand)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = -45, hjust = 0)) +
  scale_fill_manual(values = c("tomato", "orange", "green3", "yellow", "purple", "dodgerblue")) +
  labs(title = "Procentfordeling af civilstand i erhvervskategorier",
       fill = "Køn",
       x = "Erhvervskategori",
       y = "Procent")  

```



```{r}


#graf sogn og erhverv

procent_alrø_erhverv <- aarhus_data %>% 
  filter(sogn == "Alrø") %>% 
  count(sogn, Erhvervskategori) %>% 
  group_by(Erhvervskategori) %>% 
  mutate(alrø_procent = (n/sum(procent_alrø_erhverv$n))*100, round(alrø_procent, digits = 2))

#gem grafen som png
alroe_erhverv_graf <- procent_alrø_erhverv %>% 
  ggplot(aes(x = Erhvervskategori, y = alrø_procent)) + 
  geom_bar(stat = "identity") +
  geom_text(aes(label = round(alrø_procent, digits = 2), vjust = -0.5)) + 
  theme(axis.text.x = element_text(angle = -45, hjust = 0)) +
  labs(title = "Procentfordeling af erhverv i Alrø Sogn",
       x = "Erhvervskategori",
       y = "Procent") 

ggsave(alroe_erhverv_graf, )
```



```{r}

```

